# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "worldcup-pops.xcworkspace", scheme: "worldcup-pops")

    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "784e46b2aa06b89ee77d2b8ee32b29d1ed54a480",
      build_secret: "a5ad7353f271ddcd637537bad725ae070fcf9664103854151be58b8547938f32"
    )
  end
end
